#!/usr/bin/env bash
# Pool-mode entrypoint: render the dexbtx-miner config from env, then run the
# stratum client. Mirrors the config.yaml that minebtx install.sh writes, but
# driven by container env so the payout address + tuning are explicit and the
# image stays stateless. Solo mode (the default) is unaffected — this only runs
# when you start the `btx-pool` compose service (`make pool`).
set -euo pipefail

log() { echo -e "\033[1;35m[btx-pool]\033[0m $*"; }

# ── Required: payout address (a btx1z... address YOU control in your wallet) ──
ADDRESS="${BTX_PAYOUT_ADDRESS:-}"
if [ -z "$ADDRESS" ]; then
  echo "[btx-pool] ERROR: BTX_PAYOUT_ADDRESS is unset. Pool payouts would be lost." >&2
  echo "[btx-pool] Set it in docker-compose.yml (it defaults to address.txt's address)." >&2
  exit 1
fi
case "$ADDRESS" in
  btx1z*) : ;;
  *) log "WARNING: address '$ADDRESS' is not btx1z... — double-check it's your BTX payout address." ;;
esac

POOL_HOST="${BTX_POOL_HOST:-minebtx.com}"
POOL_PORT="${BTX_POOL_PORT:-3333}"
WORKER="${BTX_POOL_WORKER:-$(hostname -s 2>/dev/null || echo rig)}"

# Solver tuning. With BTX_MATMUL_GPU_INPUTS=1 (exported below, mandatory
# post-block-125000) the solver is GPU-bound, so solver_threads is a minor lever
# (12-24 within ~0.5% on a 5090); default nproc-4 clamped to [4,24], but
# docker-compose pins BTX_SOLVER_THREADS=12.
NPROC="$(nproc 2>/dev/null || echo 8)"
THREADS="${BTX_SOLVER_THREADS:-$(( NPROC-4 < 4 ? 4 : (NPROC-4 > 24 ? 24 : NPROC-4) ))}"

CONFIG=/opt/dexbtx/config.yaml
cat > "$CONFIG" <<YAML
# Generated by entrypoint-pool.sh from container env — do not hand-edit.
pool_host: "${POOL_HOST}"
pool_port: ${POOL_PORT}
pool_tls: false

payout_address: "${ADDRESS}"
worker_name: "${WORKER}"

gbt_solve_path: "/opt/dexbtx/bin/btx-gbt-solve"

solver_backend: "${BTX_SOLVER_BACKEND:-cuda}"
solver_threads: ${THREADS}
solver_batch_size: ${BTX_SOLVER_BATCH_SIZE:-128}
solver_prefetch_depth: ${BTX_SOLVER_PREFETCH:-8}
solver_prepare_workers: ${BTX_SOLVER_WORKERS:-16}
solver_pipeline_async: 1
gpu_inputs: ${BTX_GPU_INPUTS:-0}

nonces_per_slice: 2000000
reconnect_initial_s: 1.0
reconnect_max_s: 60.0
log_level: "INFO"
YAML

log "pool=${POOL_HOST}:${POOL_PORT}  worker=${WORKER}  backend=${BTX_SOLVER_BACKEND:-cuda}  threads=${THREADS}  gpu_inputs=${BTX_GPU_INPUTS:-0}"
log "payout → ${ADDRESS}"
log "NOTE: pool mode uses the pool's btx-gbt-solve (BTX v0.32.10; our PR#58 kernels now upstreamed), NOT our node solver."

# CRITICAL: btx-gbt-solve reads on-GPU input generation from the env var
# BTX_MATMUL_GPU_INPUTS, NOT from the config's gpu_inputs key. dexbtx-miner v0.4.14's
# DAEMON path stopped forwarding it (its gbt_solve_wrapper only sets the env when its
# gpu_inputs field is non-None, which the daemon path leaves None; only the benchmark
# path passes it). Without this export the solver defaults to CPU-side input gen and
# STARVES a fast GPU (5090 sat at ~3% util / ~85W, ~0 shares). The wrapper copies
# os.environ as its base env, so exporting here makes the solver subprocess inherit it.
export BTX_MATMUL_GPU_INPUTS="${BTX_GPU_INPUTS:-1}"
log "exported BTX_MATMUL_GPU_INPUTS=${BTX_GPU_INPUTS:-1} (the var the solver actually reads)"

exec dexbtx-miner --config "$CONFIG"
